window.tffo = window.tffo || {};

tffo.phrases = [
  "A bigger bang for your buck",
  "A bird in the hand is worth two in the bush",
  "A bunch of fives",
  "A chain is only as strong as its weakest link",
  "A countenance more in sorrow than in anger",
  "A Daniel come to judgement",
  "A diamond in the rough",
  "A diamond is forever",
  "A dish fit for the gods",
  "A dog is a man's best friend",
  "A drop in the bucket",
  "A drop in the ocean",
  "A fate worse than death",
  "A feather in one's cap",
  "A fish rots from the head down ",
  "A fish out of water",
  "A fly in the ointment",
  "A fool and his money are soon parted",
  "A fool's paradise",
  "A foot in the door",
  "A foregone conclusion",
  "A friend in need is a friend indeed",
  "A golden key can open any door",
  "A good man is hard to find",
  "A hard man is good to find",
  "A hiding to nothing",
  "A house divided against itself cannot stand",
  "A knight in shining armour",
  "A legend in one's own lifetime",
  "A leopard cannot change its spots",
  "A little bird told me",
  "A little knowledge is a dangerous thing",
  "A little of what you fancy does you good",
  "A load of cobblers",
  "A load of codswallop",
  "A man after my own heart",
  "A man who is his own lawyer has a fool for a client",
  "A ministering angel shall my sister be",
  "A miss is as good as a mile",
  "A nation of shopkeepers",
  "A nest of vipers",
  "A norange",
  "A picture is worth a thousand words",
  "A piece of the action",
  "A pig in a poke",
  "A place for everything and everything in its place",
  "A plague on both your houses",
  "A priori",
  "A red rag to a bull",
  "A riddle wrapped up in an enigma",
  "A rolling stone gathers no moss",
  "A rose by any other name would smell as sweet",
  "A rose is a rose is a rose",
  "A safe pair of hands",
  "A sea change",
  "A skeleton in the closet",
  "A sledgehammer to crack a nut",
  "A shot in the arm",
  "A sight for sore eyes",
  "A sorry sight",
  "A stitch in time saves nine",
  "A stone's throw",
  "A thing of beauty is a joy forever",
  "A tinker's damn",
  "A turn up for the books",
  "A watched pot never boils",
  "A wolf in sheep's clothing",
  "A woman needs a man like a fish needs a bicycle",
  "A woman's place is in the home",
  "A word in edgeways",
  "Abandon all hope ye who enter here",
  "Abide with me",
  "About face",
  "About turn",
  "Above board",
  "Abracadabra",
  "Absence makes the heart grow fonder",
  "Absent without leave",
  "Absolute power corrupts absolutely",
  "Accidentally on purpose",
  "Accidents will happen",
  "According to Hoyle",
  "Ace in the hole",
  "Achilles' heel",
  "Acid test",
  "Acronyms",
  "Across the board",
  "Act of God",
  "Act the giddy goat",
  "Action man",
  "Adam's ale",
  "Aga saga",
  "Against the grain",
  "Age before beauty",
  "Agree to disagree",
  "Aid and abet",
  "Air kiss",
  "Air quotes",
  "Al fresco",
  "Alike as two peas in a pod ",
  "Alive and kicking",
  "All agog",
  "All at sea",
  "All fingers and thumbs",
  "All in all",
  "All intents and purposes",
  "All of a sudden",
  "All present and correct",
  "All publicity is good publicity",
  "All the tea in China",
  "All things come to he who waits",
  "All things must pass",
  "All you can eat",
  "Amber nectar",
  "An albatross around one's neck",
  "An apple a day keeps the doctor away",
  "An arm and a leg ",
  "An Englishman's home is his castle",
  "An ill wind ",
  "An offer he can't refuse",
  "An Oxford scholar",
  "Anchors aweigh",
  "Angry young man",
  "Ankle biter",
  "Annus horribilis",
  "Another think coming",
  "Apple of my eye",
  "Apple pie order",
  "April fool",
  "Arms akimbo",
  "As XXX as YYY",
  "As alike as two peas in a pod ",
  "As bald as a coot",
  "As black as Newgate's knocker",
  "As brown as a berry",
  "As busy as a bee",
  "As cold as any stone",
  "As cool as a cucumber",
  "As cute as a bug's ear",
  "As daft as a brush",
  "As dead as a dodo",
  "As dead as a doornail",
  "As different as chalk and cheese",
  "As easy as pie ",
  "As fast as greased lightning",
  "As fine as frog's hair",
  "As fit as a butcher's dog",
  "As fit as a fiddle",
  "As good as gold",
  "As good luck would have it",
  "As happy as a clam",
  "As happy as a sandboy",
  "As happy as Larry",
  "As keen as mustard",
  "As mad as a hatter",
  "As mad as a March hare",
  "As nice as ninepence",
  "As old as Methuselah",
  "As old as the hills",
  "As pleased as Punch",
  "As pure as the driven snow",
  "As queer as a nine bob note",
  "As snug as a bug in a rug",
  "As straight as a die",
  "As the crow flies",
  "As white as snow",
  "Ashes to ashes dust to dust",
  "Ask a silly question and you'll get a silly answer",
  "At loggerheads",
  "At one fell swoop",
  "At one's beck and call",
  "At sixes and sevens",
  "Auld lang syne",
  "Away with the fairies",
  "Baby blues",
  "Baby boomer",
  "Baby father",
  "Back of beyond",
  "Back the field",
  "Back to basics",
  "Back to square one",
  "Back to the drawing board",
  "Backroom boy",
  "Bacon",
  "Bad books",
  "Bad egg",
  "Bad hair day",
  "Badger to death",
  "Bag and baggage",
  "Baker's dozen",
  "Balance of power",
  "Balance of trade",
  "Bald as a coot",
  "Ball and chain",
  "Bandy words ",
  "Bane of your life",
  "Bang on about",
  "Baptism of fire",
  "Barking mad",
  "Barking up the wrong tree",
  "Basket case",
  "Bated breath",
  "Bats in the belfry",
  "Batten down the hatches",
  "Battle royal",
  "Be enthralled",
  "Beam ends",
  "Bean counter",
  "Beast with two backs",
  "Beat a hasty retreat",
  "Beat around the bush",
  "Beat swords into ploughshares",
  "Beat the living daylights out of someone",
  "Beauty is in the eye of the beholder",
  "Beauty is only skin deep",
  "Beck and call",
  "Bed of roses",
  "Bee in your bonnet",
  "Beef and reef",
  "Beelzebub has a devil for a sideboard",
  "Beer and skittles",
  "Bee's knees",
  "Before you can say Jack Robinson ",
  "Beg the question",
  "Beggar belief",
  "Beggars can't be choosers",
  "Behind every great man there's a great woman",
  "Behind the eight ball",
  "Bell the cat",
  "Belle of the ball",
  "Below the belt",
  "Below the salt",
  "Bells and whistles",
  "Belt and braces",
  "Belt up",
  "Best bib and tucker",
  "Best laid schemes of mice and men",
  "Bet your bottom dollar",
  "Better half ",
  "Better late than never",
  "Better to have loved and lost than never to have loved at all",
  "Between a rock and a hard place",
  "Between the Devil and the deep blue sea",
  "Between two stools",
  "Beware of Greeks bearing gifts",
  "Beware the Ides of March ",
  "Beyond belief",
  "Beyond our ken",
  "Beyond the pale",
  "Biblical phrases",
  "Big Apple",
  "Big cheese",
  "Big Easy",
  "Big fish in a small pond",
  "Big wig",
  "Bill Stickers is innocent",
  "Billy no mates",
  "Binge drinking",
  "Bird in the hand is worth two in the bush",
  "Birds and the bees",
  "Birds of a feather flock together",
  "Bite the bullet",
  "Bite the dust",
  "Bitter end",
  "Black as Newgate's knocker",
  "Black sheep of the family",
  "Blast from the past",
  "Blaze a trail",
  "Blind leading the blind",
  "Blonde bombshell",
  "Blood and thunder",
  "Blood is thicker than water",
  "Blood toil tears and sweat",
  "Blot on the landscape",
  "Blow your mind",
  "Blow your own trumpet",
  "Blown to smithereens",
  "Blue blood",
  "Bob's your uncle",
  "Bode well",
  "Bodice ripper",
  "Body surfing",
  "Bog standard",
  "Bolt from the blue",
  "Bone dry",
  "Bone idle",
  "Bone up on",
  "Booby prize",
  "Booby trap",
  "Booze cruise",
  "Born again",
  "Born with a silver spoon in one's mouth",
  "Born within the sound of Bow Bells",
  "Boss eyed",
  "Bottle out",
  "Bottom drawer",
  "Bought the farm",
  "Bowled a maiden over",
  "Box and Cox",
  "Boxing Day",
  "Brand spanking new",
  "Brass monkey weather ",
  "Brass tacks",
  "Bread always falls buttered side down",
  "Bread of life",
  "Break a leg",
  "Break the ice",
  "Bricks and clicks",
  "Bring home the bacon",
  "Broad in the beam",
  "Broke",
  "Brook no truck with",
  "Brown as a berry",
  "Browned off",
  "Brownie points",
  "Brummagem screwdriver",
  "Brush",
  "Bubble and squeak",
  "Buck stops here",
  "Buckle down",
  "Buggins' turn",
  "Bullet",
  "Bums on seats",
  "Bun in the oven",
  "Bunch of fives",
  "Bunny boiler",
  "Burn the candle at both ends",
  "Burning the midnight oil",
  "Bury the hatchet",
  "Bury your head in the sand",
  "Busy as a bee",
  "Butter side down",
  "Butter wouldn't melt in his mouth",
  "Butterfingers",
  "By and large",
  "By dint of",
  "By gum",
  "By hook or by crook",
  "By the board",
  "By the book",
  "By the short hairs",
  "By the skin of your teeth",
  "By your leave",
  "Call a spade a spade",
  "Call of the wild",
  "Camera cannot lie",
  "Can't hold a candle to",
  "Canteen culture",
  "Carbon footprint",
  "Carpe diem",
  "Carry coals to Newcastle",
  "Cart before the horse",
  "Carte blanche",
  "Cash on the nail",
  "Cast the first stone",
  "Cat may look at a king",
  "Cat out of the bag",
  "Cat's Cradle",
  "Caught in a cleft stick",
  "Caught by the short hairs",
  "Chain is only as strong as its weakest link",
  "Chaise lounge",
  "Chalk and cheese",
  "Champ at the bit",
  "Charley horse",
  "Charm offensive",
  "Charmed life",
  "Cheap at half the price",
  "Cherchez la femme",
  "Chew the cud",
  "Chick flick",
  "Chickens come home to roost",
  "Children should be seen and not heard",
  "Chinese whispers",
  "Chinless wonder",
  "Chip off the old block",
  "Chip on your shoulder",
  "Chop and change",
  "Chow down",
  "Christmas box",
  "Christmas card verses",
  "Clean breast ",
  "Clear blue water",
  "Cleft stick",
  "Climb on the bandwagon",
  "Cloak and dagger",
  "Clog up",
  "Close quarters",
  "Close your eyes and think of England",
  "Cloud cuckoo land",
  "Cloud nine",
  "Clue",
  "Clutch at straws",
  "Coals to Newcastle",
  "Cobblers",
  "Cock a snook",
  "Cock and bull story",
  "Cockney rhyming slang",
  "Codswallop",
  "Cogito ergo sum",
  "Coin a phrase",
  "Cold as any stone",
  "Cold comfort",
  "Cold enough to freeze the balls off a brass monkey",
  "Cold feet",
  "Cold shoulder",
  "Cold turkey",
  "Collywobbles",
  "Colour up ",
  "Come a cropper",
  "Come clean",
  "Come on down",
  "Come up trumps",
  "Come what come may",
  "Comes to the crunch",
  "Common sense",
  "Comparisons are odious",
  "Compassion fatigue",
  "Complete shambles",
  "Cook the books",
  "Cookie cutter",
  "Cool as a cucumber",
  "Cool Britannia",
  "Cop an attitude",
  "Cor blimey",
  "Cordon bleu",
  "Cost an arm and a leg ",
  "Cotton on to",
  "Countenance more in sorrow than in anger",
  "Counting sheep",
  "Course of true love never did run smooth",
  "Crack of doom",
  "Crackpot",
  "Crapper",
  "Crop up",
  "Crocodile tears",
  "Cry havoc and let slip the dogs of war",
  "Curate's egg",
  "Curiosity killed the cat",
  "Curry favour",
  "Customer is always right",
  "Cut and run",
  "Cut of your jib",
  "Cut off without a penny",
  "Cut off your nose to spite your face",
  "Cut the mustard",
  "Cut to the chase",
  "Cute as a bug's ear",
  "Daft as a brush",
  "Damp squib",
  "Dance attendance on",
  "Daniel come to judgement",
  "Darby and Joan",
  "Dark horse",
  "Darkest hour is just before the dawn",
  "Dark side",
  "Darling buds of May",
  "Dash to pieces",
  "Date rape",
  "Davy Jones' locker",
  "Daylight robbery",
  "Dead as a dodo",
  "Dead as a doornail",
  "Dead cat bounce",
  "Dead ringer",
  "Delusions of grandeur",
  "Designer stubble",
  "Deus ex machina",
  "Devil and the deep blue sea ",
  "Devil Incarnate",
  "Devil take the hindmost",
  "Devil to pay",
  "Diamond in the rough",
  "Diamond is forever",
  "Die has been cast",
  "Different kettle of fish",
  "Differently abled",
  "Dirt bag",
  "Dish fit for the gods",
  "Do unto others as you would have them do to you",
  "Dock your pay",
  "Doesn't know shit from Shinola",
  "Doff your hat",
  "Dog days",
  "Dog in the manger",
  "Dog is a man's best friend",
  "Dog's bollocks",
  "Dog's breakfast",
  "Dog's dinner",
  "Doldrums",
  "Dollars to donuts",
  "Done a runner",
  "Done to a turn",
  "Donkey's years",
  "Don't change horses in midstream",
  "Don't count your chickens before they are hatched",
  "Don't die like I did",
  "Don't go there",
  "Don't have a clue",
  "Don't keep a dog and bark yourself",
  "Don't let the bastards grind you down",
  "Don't look a gift horse in the mouth",
  "Don't throw the baby out with the bathwater",
  "Don't try to teach your Grandma to suck eggs",
  "Doom and gloom",
  "Double cross",
  "Double Dutch",
  "Double whammy",
  "Down at heel",
  "Down in the dumps",
  "Down the pan",
  "Down the tubes",
  "Drag race",
  "Draw a blank",
  "Draw your horns in",
  "Dreams of empire",
  "Dressed to the nines",
  "Drink like a fish",
  "Driving while black",
  "Drop in the bucket",
  "Dropping like flies",
  "Drummed out of the army",
  "Ducks and drakes",
  "Dust up",
  "Dutch",
  "Duvet day",
  "Ear candy",
  "Early bird catches the worm",
  "Easy as pie ",
  "Eat drink and be merry",
  "Eat humble pie",
  "Eat my hat",
  "Eaten out of house and home",
  "Economical with the truth",
  "Egg on",
  "Eighty six",
  "Elementary my dear Watson",
  "Elephant in the room",
  "Elvis has left the building",
  "End of story",
  "Ends of the earth ",
  "Englishman's home is his castle",
  "Ethnic cleansing",
  "Even at the turning of the tide",
  "Every cloud has a silver lining",
  "Everybody out",
  "Exceedingly well read",
  "Excuse me while I kiss this guy",
  "Excuse my French",
  "Extraordinary rendition",
  "Face that launched a thousand ships",
  "Face the music",
  "Faff about",
  "Fair and square",
  "Fair play",
  "Fair to middling",
  "Fait accompli ",
  "Faith will move mountains",
  "Fall from grace",
  "Fall guy",
  "Fall off the back of a lorry",
  "Fall on your sword",
  "Famous for fifteen minutes",
  "Famous last words",
  "Famous last words",
  "Fancy free",
  "Fancy pants",
  "Fanny Adams",
  "Far be it from me",
  "Far from the madding crowd",
  "Farmers",
  "Fashion victim",
  "Fast and loose",
  "Fast asleep",
  "Fathom out",
  "Fate worse than death",
  "Feather in one's cap",
  "Fed up",
  "Feeding frenzy",
  "Fell swoop",
  "Fellow traveller",
  "Female of the species is more deadly then the male",
  "Fiddling while Rome burns",
  "Field day",
  "Fifteen minutes of fame",
  "Fifth column",
  "Fight fire with fire",
  "Fight the good fight",
  "Filthy rich",
  "Finagle's Law",
  "Fine as frog's hair",
  "Fine words butter no parsnips",
  "Finger lickin good",
  "Fingers and thumbs",
  "First water",
  "First World",
  "Fish rot from the head down ",
  "Fish or cut bait",
  "Fish out of water",
  "As fit as a butcher's dog",
  "Fit as a fiddle",
  "Fits and starts",
  "Fits to a tee",
  "Five o'clock shadow",
  "Flash in the pan",
  "Flat out",
  "Flavor of the month",
  "Flesh and blood",
  "Flogging a dead horse",
  "Floozie in the jacuzzi",
  "Flotsam and jetsam",
  "Fly by the seat of one's pants",
  "Fly in the ointment",
  "Fly off the handle",
  "Fly on the wall",
  "Foam at the mouth",
  "Fobbed off",
  "Folk Etymology",
  "Fool and his money are soon parted",
  "Fools rush in where angels fear to tread",
  "Fools' gold",
  "Fool's paradise",
  "Foot in the door",
  "Foot of our stairs",
  "For all intents and purposes",
  "For crying out loud",
  "For ever and a day",
  "For every thing there is a season",
  "For good measure",
  "For keeps",
  "For the birds",
  "For whom the bell tolls",
  "Forbidden fruit",
  "Foregone conclusion",
  "Forewarned is forearmed",
  "Forgive them for they know not what they do",
  "Forlorn hope",
  "Foul play",
  "Four by two",
  "Four corners of the earth",
  "Freeze the balls off a brass monkey",
  "Freezing temperatures",
  "French phrases",
  "Friday afternoon car",
  "Friend in need is a friend indeed",
  "Frog in the throat",
  "Frog's hair",
  "From sea to shining sea",
  "From strength to strength",
  "Fruits of your loins",
  "Full Monty",
  "Full of piss and vinegar",
  "Full tilt",
  "Full to the gunwales",
  "Funny farm",
  "Fuzzy wuzzy",
  "Gad zooks",
  "Game is afoot",
  "Game is up",
  "Game of two halves",
  "Gee whiz",
  "Generation X",
  "Get a word in edgeways",
  "Get down to brass tacks",
  "Get off on the wrong foot",
  "Get off your high horse",
  "Get on my wick",
  "Get one's dander up",
  "Get over it",
  "Get the pip",
  "Get the sack",
  "Get the upper hand",
  "Get thee behind me Satan",
  "Get underway",
  "Get used to it",
  "Get your dander up",
  "Get your goat",
  "Giddy aunt",
  "Giddy goat",
  "Gild the lily",
  "Gilt off the gingerbread",
  "Ginned up ",
  "Ginger",
  "Ginger up ",
  "Give a man a fish and you will feed him for a day",
  "Give no quarter",
  "Give up the ghost",
  "Glass ceiling",
  "Gloom and doom",
  "Go and boil your head",
  "Go berserk",
  "Go by the board",
  "Go by the book",
  "Go Dolally",
  "Go for a burton",
  "Go haywire ",
  "Go like the clappers",
  "Go out on a limb",
  "Go postal",
  "Going to hell in a handbasket",
  "Go pound sand",
  "Go the whole hog",
  "Go to pot",
  "Go to the dogs",
  "Go to the foot of our stairs",
  "Go to the mattresses",
  "Go whole hog",
  "God is dead",
  "God rot them",
  "Godfrey Daniel",
  "Going for a burton",
  "Golden key can open any door",
  "Gone for a burton",
  "Good as gold",
  "Good in parts",
  "Good man is hard to find",
  "Good measure",
  "Good men and true",
  "Good riddance",
  "Good Samaritan",
  "Gordon Bennett",
  "Got my mojo working",
  "Grace of God",
  "Grand slam",
  "Grandfather clock",
  "Granny dumping",
  "Grasp the nettle",
  "Grass up",
  "Graveyard shift",
  "Greased lightning",
  "Great minds think alike",
  "Great unwashed",
  "Green eyed monster",
  "Gregory Peck",
  "Gridlock",
  "Grind to a halt",
  "Grinning like a Cheshire cat",
  "Grist to the mill",
  "Guinea pig",
  "Gung ho",
  "Guts for garters",
  "Hair of the dog that bit you",
  "Hairy eyeball",
  "Halcyon days",
  "Half inch",
  "Hand over fist",
  "Handbags at ten paces",
  "Handle with kid gloves",
  "Hands down",
  "Happy as a clam",
  "Happy as a sandboy",
  "Happy as Larry",
  "Happy clappy",
  "Happy slapping",
  "Harbinger of doom",
  "Hard and fast",
  "Hard cases make bad law",
  "Hard cheese ",
  "Hard hearted",
  "Hard lines",
  "Hard man is good to find",
  "Harp on",
  "Hat trick",
  "Have a Captain Cook",
  "Have an axe to grind",
  "Have an inkling",
  "Have no truck with",
  "Haven't got a clue",
  "Have your guts for garters",
  "He who laughs last laughs longest",
  "He will give the Devil his due",
  "Head over heels",
  "Heads up",
  "Hear hear",
  "Heard it through the grapevine",
  "Heart's content",
  "Heavens to Betsy",
  "Heavens to Murgatroyd",
  "Heavy metal",
  "Hedge your bets",
  "Hell in a handbasket",
  "Hell has no fury like a woman scorned",
  "Hell or high water",
  "Here lies one whose name is writ in water",
  "Het up",
  "Hiding to nothing",
  "High and dry",
  "High and mighty",
  "High five",
  "High horse",
  "High on the hog",
  "High time",
  "Hissy fit",
  "History is bunk",
  "Hit the ground running",
  "Hit the hay",
  "Hit the nail on the head",
  "Hobson's choice",
  "Hocus pocus",
  "Hoi polloi",
  "Hoist with your own petard",
  "Hold your horses",
  "Homonyms",
  "Honesty is the best policy",
  "Hooray Henry",
  "Horse and cart",
  "Horse feathers",
  "Horse's mouth",
  "Hot off the press",
  "Hot on the heels",
  "House divided against itself cannot stand",
  "Household words",
  "How sharper than a serpent's tooth it is to have a thankless child",
  "Hunt and peck",
  "Hush puppies",
  "I bear a charmed life",
  "I have not slept one wink",
  "I have nothing to declare but my genius",
  "I have nothing to offer but blood toil tears and sweat",
  "I haven't got a clue",
  "I see you stand like greyhounds in the slips",
  "I spy with my little eye",
  "I told you is was ill",
  "I will swing for you",
  "I will wear my heart upon my sleeve",
  "Identity theft",
  "If I had my druthers",
  "If the cap fits",
  "If the shoe fits",
  "Ill wind ",
  "I'll be there with bells on",
  "I'll go to the foot of our stairs",
  "I'll have your guts for garters",
  "I'm stumped",
  "Imitation is the sincerest form of flattery",
  "In a cleft stick",
  "In a pickle",
  "In a pig's eye",
  "In a quandary",
  "In a trice",
  "In an interesting condition",
  "In like Flynn",
  "In limbo",
  "In my minds eye",
  "In someone's bad books",
  "In spades",
  "In stitches",
  "In the bag",
  "In the buff",
  "In the cart",
  "In the catbird seat",
  "In the club",
  "In the doghouse",
  "In the doldrums",
  "In the limelight",
  "In the nick of time ",
  "In the offing",
  "In the pink",
  "In the red",
  "In the sticks",
  "In the twinkling of an eye",
  "In trouble",
  "In your face",
  "Indian giver",
  "Indian summer",
  "Infra dig",
  "Innocent until proven guilty",
  "Inside out",
  "Iron hoof",
  "It ain't over till the fat lady sings",
  "It came like a bolt from the blue",
  "It is meat and drink to me",
  "It never rains but it pours",
  "It's all grist to the mill",
  "It's better to give than to receive",
  "It's better to light a candle than curse the darkness",
  "It's not rocket science",
  "It's that man again",
  "Ivory tower",
  "Jack in the box",
  "Jack Palancing",
  "Jack Robinson ",
  "Jack the lad",
  "Jam tomorrow",
  "Jerry built",
  "Jimmy Horner",
  "Jimmy Riddle",
  "Jobs for the boys",
  "Join the colours",
  "Joined at the hip",
  "Johnny on the spot",
  "Jot or tittle",
  "Jump on the bandwagon",
  "Jump the gun",
  "Jump the shark",
  "Jury is still out",
  "Just deserts",
  "Just in time",
  "Kangaroo court",
  "Katy bar the door",
  "Keep a wide berth",
  "Keen as mustard",
  "Keep body and soul together",
  "Keep schtum",
  "Keep a stiff upper lip",
  "Keep it under your hat",
  "Keep the ball rolling",
  "Keep up with the Joneses",
  "Keep your chin up",
  "Keep your hands clean ",
  "Keep your nose clean ",
  "Keep your nose to the grindstone",
  "Keep your pecker up",
  "Keep your powder dry",
  "Kettle of fish",
  "Khyber pass",
  "Kick the bucket",
  "Kick your heels",
  "Kickin' ",
  "Kilroy was here",
  "King James' Version of the Bible",
  "Kiss and tell",
  "Kiss me Hardy",
  "Knight in shining armour",
  "Knock back",
  "Knock into a cocked hat ",
  "Knock off",
  "Knock on wood",
  "Know the ropes",
  "Know your onions",
  "Know which way the wind blows",
  "Knuckle down",
  "Knuckle under",
  "La dolce vita",
  "Labour of love",
  "Lackadaisical",
  "Lager frenzy",
  "Laid out in lavender",
  "Lamb to the slaughter",
  "Lame duck",
  "Land of nod",
  "Lark about",
  "Last but not least",
  "Last straw",
  "Latin Phrases",
  "Laugh like a drain",
  "Laurels",
  "Lay it on with a trowel",
  "Lead balloon",
  "Learn the ropes",
  "Left hand doesn't know what the right hand is doing",
  "Left in the lurch",
  "Leopard cannot change its spots",
  "Less is more",
  "Let a thousand flowers bloom",
  "Let bygones be bygones",
  "Let not poor Nelly starve",
  "Let not the sun go down on your wrath",
  "Let or hindrance ",
  "Let the cat out of the bag",
  "Let them eat cake",
  "Let there be light",
  "Let your hair down",
  "Let's roll",
  "Level playing field",
  "Lick and a promise",
  "Lick into shape",
  "Lie low",
  "Life begins at forty",
  "Life of Riley",
  "Life's not all beer and skittles",
  "Life's too short",
  "Like a chicken with its head cut off",
  "Like a moth to a flame",
  "Like being savaged by a dead sheep",
  "Like it or lump it",
  "Like the clappers",
  "Like the Dickens",
  "Like two peas in a pod ",
  "Little bird told me",
  "Little knowledge is a dangerous thing",
  "Little of what you fancy does you good",
  "Lions led by donkeys",
  "Live long and prosper",
  "Living daylights",
  "Living off the fat of the land",
  "Living on borrowed time",
  "Lo and behold",
  "Load of cobblers",
  "Load of codswallop",
  "Loaf of bread",
  "Local derby",
  "Lock stock and barrel",
  "Long in the tooth",
  "Look before you leap",
  "Loose cannon",
  "Loose lips sink ships",
  "Lose face",
  "Lose your marbles",
  "Love is blind ",
  "Love that dare not speak its name",
  "Mad as a hatter",
  "Magical realism",
  "Main chance",
  "Make a clean breast of it",
  "Make a pig's ear of",
  "Make a virtue of necessity",
  "Make haste",
  "Make hay while the sun shines",
  "Make him an offer he can't refuse",
  "Make my day",
  "Make no bones about",
  "Make your hair stand on end",
  "Mal de mer",
  "Man after my own heart",
  "Man does not live by bread alone",
  "Man who is his own lawyer has a fool for a client",
  "Man's inhumanity to man",
  "Many a little makes a mickle",
  "Many are called but few are chosen",
  "Many happy returns",
  "Many a true word is spoken in jest",
  "Mare's nest",
  "Marital aid ",
  "Market forces",
  "May you live in interesting times",
  "Mea culpa",
  "Meat and two veg",
  "Meet your Waterloo",
  "Men in suits",
  "Mend fences",
  "Merry Christmas",
  "Mexican wave",
  "Mickey Finn",
  "Middle for diddle",
  "Middle of the road",
  "Might and main",
  "Mighty oaks from little acorns grow",
  "Milk of human kindness",
  "Minced oaths",
  "Mind your Ps and Qs",
  "Ministering angel shall my sister be",
  "Misery acquaints a man with strange bedfellows",
  "Misquotes",
  "Miss is as good as a mile",
  "Moaning Minnie",
  "Mondegreens",
  "Montezuma's Revenge",
  "Moot point",
  "Morbid obesity",
  "More bangs for your buck",
  "More fool you",
  "More honoured in the breach than in the observance",
  "Morning person",
  "Mother country",
  "Motley crew",
  "Moveable feast",
  "Movers and shakers",
  "Moving finger writes",
  "Moving the goalposts",
  "Much Ado about Nothing",
  "Much of a muchness",
  "Mud",
  "Multitude of sins",
  "Mumbo jumbo",
  "Mum's the word",
  "Murphy's Law",
  "Music has charms to soothe the savage breast",
  "Mutt's nuts",
  "Mutt and Jeff",
  "Mutton dressed as lamb",
  "My bad ",
  "My better half ",
  "My cup of tea",
  "My cup runneth over",
  "My giddy aunt",
  "My husband and I",
  "My mind's eye",
  "My old china",
  "My old Dutch",
  "My salad days",
  "My stars and garters",
  "Nail your colours to the mast",
  "Name and shame",
  "Name is mud",
  "Nation of shopkeepers",
  "Nautical phrases",
  "Necessity is the mother of invention",
  "Ne'er cast a clout till May be out",
  "Ne'er do well",
  "Needs must ",
  "Neither a borrower nor a lender be",
  "Neither here nor there",
  "Nest of vipers",
  "Never give a sucker an even break",
  "Never knowingly undersold",
  "Never look a gift horse in the mouth",
  "Never the twain shall meet",
  "New kid on the block",
  "Nice as ninepence",
  "Nice kettle of fish",
  "Night owl",
  "Nine days' wonder",
  "Nip and tuck",
  "Nip in the bud",
  "No dice",
  "No holds barred",
  "No laughing matter",
  "No man is an island",
  "No quarter given",
  "No rest for the wicked",
  "No room to swing a cat",
  "No truck with",
  "Nod is as good as a wink",
  "Nod",
  "Norange",
  "Nosy parker",
  "Not my cup of tea",
  "Not for all the tea in China",
  "Not playing with a full deck",
  "Not rocket science",
  "Not tonight Josephine",
  "Not worth a plugged nickel",
  "Not worth the candle",
  "Nothing is certain but death and taxes",
  "Nothing succeeds like success",
  "Now is the winter of our discontent",
  "Nth degree ",
  "Nul points",
  "Odds bodkins",
  "Off his own bat",
  "Off the record",
  "Off with his head",
  "Okay",
  "Old as Methuselah",
  "Old as the hills",
  "Old chestnut",
  "Old codger",
  "Old hat",
  "On a hiding to nothing",
  "On a wing and a prayer",
  "On Carey Street",
  "On cloud nine",
  "On queer street",
  "On tenterhooks",
  "On the ball",
  "On the bubble",
  "On the button",
  "On the dole",
  "On the fiddle",
  "On the pig's back",
  "On the QT",
  "On the shoulders of giants",
  "On the wagon",
  "On the warpath",
  "On with the motley",
  "On your beam ends",
  "On your tod",
  "Once in a blue moon",
  "One fell swoop",
  "One for the road",
  "One over the eight",
  "One sandwich short of a picnic",
  "One small step for man",
  "One stop shop",
  "One swallow doesn't make a summer",
  "One's heart's content",
  "Open season",
  "Out of sorts",
  "Out of the jaws of death",
  "Out of the mouths of babes and sucklings",
  "Over a barrel",
  "Over the moon",
  "Over the top",
  "Oxo cube",
  "Ps and Qs",
  "Paddle your own canoe",
  "Paint the town red",
  "Panic stations",
  "Paper tiger",
  "Pass the buck",
  "Pearls before swine",
  "Pears for your heirs",
  "Peeping Tom",
  "Peg out",
  "Penny saved is a penny earned",
  "Pester power",
  "Peter out",
  "Petty cash",
  "Physician heal thyself",
  "Pick 'n' mix ",
  "Picture is worth a thousand words",
  "Pie",
  "Pie in the sky",
  "Piece of cake",
  "Piece of piss",
  "Piece of the action",
  "Pig in a poke",
  "Pig's back",
  "Pig's ear",
  "Pig and whistle",
  "Piggyback",
  "Pigs might fly",
  "Pin money",
  "Pip",
  "Pipe down",
  "Pipe dream",
  "Piping hot",
  "Piss and vinegar",
  "Place for everything and everything in its place",
  "Plague on both your houses",
  "Plain sailing",
  "Plates of meat",
  "Play by ear",
  "Play ducks and drakes",
  "Play fast and loose",
  "Play it again Sam",
  "Play silly buggers",
  "Play the giddy goat",
  "Play the race card",
  "Pleased as Punch",
  "Plug ugly",
  "Plugged nickel",
  "Poetic justice",
  "Point Percy at the porcelain",
  "Politically correct",
  "Point to point",
  "Pommy bashing",
  "Pond life",
  "Pony and trap",
  "Pony up",
  "Pop goes the weasel",
  "Popular fallacies",
  "Pork pies",
  "Pot calling the kettle black",
  "Pound of flesh",
  "Pour oil on troubled waters",
  "Power dressing",
  "Powers that be",
  "Praying at the porcelain altar",
  "Preaching to the choir",
  "Preposterous",
  "Press into service",
  "Pretty kettle of fish",
  "Prick up your ears",
  "Prime time",
  "Primrose path",
  "Proof of the pudding is in the eating",
  "Proverbs",
  "Pull in your horns",
  "Pull out all the stops",
  "Pull the wool over your eyes",
  "Pull up stakes",
  "Pull your horns in",
  "Pull yourself up by your bootstraps",
  "Punch above one's weight",
  "Pure as the driven snow",
  "Purple patch",
  "Push the boat out",
  "Push the envelope",
  "Put a damper on",
  "Put a sock in it",
  "Put a spanner in the works",
  "Put on the wooden overcoat",
  "Put on your thinking cap",
  "Put paid to",
  "Put the cart before the horse",
  "Put the mockers on",
  "Put the wood in the hole",
  "Put up your dukes",
  "Put your back up",
  "Put your best foot forward",
  "Put your nose out of joint ",
  "Pyrric victory",
  "Quality time",
  "Quarter",
  "Queer as a nine bob note",
  "Queer Street",
  "Queer the pitch",
  "Quick and the dead",
  "Quicker than lager turns to piss",
  "Quid pro quo",
  "Quotations",
  "Rabbit and pork",
  "Rack and ruin",
  "Rack your brains",
  "Raining cats and dogs",
  "Raise Cain",
  "Rank and file",
  "Raspberry tart",
  "Raze to the ground",
  "Rat arsed",
  "Read between the lines",
  "Read the riot act",
  "Real McCoy",
  "Red herring",
  "Red in tooth and claw",
  "Red letter day",
  "Red rag to a bull",
  "Red tape",
  "Reduplicated phrases",
  "Religion is the opium of the people ",
  "Rest on his laurels",
  "Revenge is a dish best served cold",
  "Rhyme nor reason",
  "Rhyming slang",
  "Richard of York gave battle in vain",
  "Richard the Third",
  "Riddle wrapped up in an enigma",
  "Riding shotgun",
  "Riley",
  "Ring down the curtain",
  "Ring the changes",
  "Rise and shine",
  "Road less travelled",
  "Road apples",
  "Road rage",
  "Roasted to a turn",
  "Rob Peter to pay Paul",
  "Rock and roll ",
  "A rolling stone gathers no moss",
  "Rose by any other name would smell as sweet",
  "Rose is a rose is a rose",
  "Rosie Lea",
  "Rough diamond",
  "Round Robin",
  "Route one",
  "Rub of the green",
  "Rule of thumb",
  "Rum do",
  "Run a mile",
  "Run amok",
  "Run of the mill",
  "Run out of steam",
  "Run rings around",
  "Run the gauntlet",
  "Sacred cow",
  "Safe pair of hands",
  "Safe sex",
  "Salad days",
  "Salt of the earth",
  "San fairy Ann",
  "Sandwich short of a picnic",
  "Save face",
  "Save one's bacon ",
  "Saved by the bell",
  "Savoir faire",
  "Say cheese",
  "Say goodnight Gracie",
  "Scarper",
  "Scot free",
  "Scott",
  "Screw your courage to the sticking place",
  "Sea change",
  "Sealed with a loving kiss",
  "Season of mists and mellow fruitfulness",
  "Security blanket",
  "See red",
  "Seen better days",
  "Send packing",
  "Senior citizen",
  "Sent to Coventry",
  "Separate the sheep from the goats",
  "Set one's cap at",
  "Set your teeth on edge",
  "Sex and shopping",
  "Sexton Blake",
  "Shebang",
  "Shaggy dog story",
  "Shake a leg",
  "Shakers and movers",
  "Shakespeare",
  "Shambles",
  "Share and share alike",
  "Ship shape and Bristol fashion",
  "Shit for brains",
  "Shiver my timbers",
  "Short end of the stick",
  "Shot across the bows",
  "Shot heard 'round the world",
  "Shot in the arm",
  "Shot in the dark",
  "Shoot through",
  "Short shrift",
  "Show your mettle",
  "Shuffle off this mortal coil",
  "Sick puppy",
  "Sight for sore eyes",
  "Silly Billy",
  "Silly season",
  "Silver lining",
  "Sir Walter Scott",
  "Silence is golden",
  "Silver bullet",
  "Similes",
  "Sixes and sevens",
  "Skeleton in the closet",
  "Skid row",
  "Skin and blister",
  "Sledgehammer to crack a nut",
  "Sleep like a top",
  "Sleep on a clothesline",
  "Sleep tight",
  "Sloane Ranger",
  "Slush fund",
  "Smallest room in the house",
  "Smart casual",
  "Smoke and mirrors",
  "Snug as a bug in a rug",
  "So sue me",
  "Sod's Law",
  "Sold down the river",
  "Someone is walking over my grave",
  "Son of a gun",
  "Sorry sight",
  "Sound bite",
  "Sound out",
  "Sour grapes",
  "Spare the rod and spoil the child",
  "Speak of the Devil",
  "Speak softly and carry a big stick",
  "Special relationship",
  "Spend a penny",
  "Spick and span",
  "Spill the beans",
  "Spin doctor",
  "Spitting feathers",
  "Spitting image",
  "Square meal",
  "Squeaky bum time",
  "Stand and deliver",
  "Stand up guy",
  "Standing on the shoulders of giants",
  "Stars and garters",
  "Start from scratch",
  "Steal a march",
  "Steal my thunder",
  "Stick in the mud",
  "Sticks and stones may break my bones",
  "Sticky wicket",
  "Stiff upper lip",
  "Stiffen the sinews",
  "Stinking rich",
  "Stitch in time saves nine",
  "Stone the crows",
  "Stone's throw",
  "Stool pigeon",
  "Storm in a teacup",
  "Straight as a die",
  "Straight from the horse's mouth",
  "Strain at the leash",
  "Strait and narrow",
  "Stranger danger",
  "Stranger than fiction",
  "Strike while the iron is hot",
  "Stuff and nonsense",
  "Stump up",
  "Such is life",
  "Surf and turf",
  "Survival of the fittest",
  "Suspension of disbelief",
  "Swan song",
  "Sweet Fanny Adams",
  "Swing for you",
  "Swing the lead",
  "Tail wagging the dog",
  "Take a back seat",
  "Take down a peg or two",
  "Take potluck ",
  "Take the bit between your teeth",
  "Take the cake",
  "Take the gilt off the gingerbread",
  "Take the Mickey",
  "Take the upper hand",
  "Take umbrage ",
  "Take with a grain of salt",
  "Taken aback",
  "Talk of the Devil",
  "Talk the talk",
  "Talk through one's hat",
  "Talk to the hand",
  "Tall story",
  "Tattoo phrases and sayings",
  "Tawdry",
  "Tea leaf",
  "Technicolor yawn",
  "Tell it to the marines",
  "Tempest in a teapot",
  "That's all she wrote",
  "The apple of my eye",
  "The back of beyond",
  "The balance of power",
  "The balance of trade",
  "The bane of my life",
  "The bee's knees",
  "The belle of the ball",
  "The best laid schemes of mice and men",
  "The Big Apple",
  "The Big Easy",
  "The birds and the bees",
  "The bitter end",
  "The blind leading the blind",
  "The bread of life",
  "The buck stops here",
  "The call of the wild",
  "The camera cannot lie",
  "The chickens come home to roost",
  "The collywobbles",
  "The course of true love never did run smooth",
  "The crack of doom",
  "The Crapper",
  "The customer is always right",
  "The cut of your jib",
  "The dark side",
  "The darkest hour is just before the dawn",
  "The Devil Incarnate",
  "The Devil take the hindmost",
  "The Devil to pay",
  "The die has been cast",
  "The early bird catches the worm",
  "The elephant in the room",
  "The ends of the earth ",
  "The exception which proves the rule",
  "The face that launched a thousand ships",
  "The fat of the land",
  "The female of the species is more deadly then the male",
  "The floozie in the jacuzzi",
  "The fly in the ointment",
  "The full monty",
  "The game is afoot",
  "The game is up",
  "The great unwashed",
  "The hair of the dog that bit you",
  "The hairy eyeball",
  "The jury is still out",
  "The land of nod",
  "The last straw",
  "The law is an ass",
  "The life of Riley",
  "The living daylights",
  "The love that dare not speak its name",
  "The moving finger writes",
  "The mutt's nuts",
  "The nth degree ",
  "The opera ain't over till the fat lady sings",
  "The pen is mightier than the sword ",
  "The pip",
  "The pot calling the kettle black",
  "The powers that be",
  "The proof of the pudding is in the eating ",
  "The quick and the dead",
  "The real McCoy",
  "The road less travelled",
  "The salt of the earth ",
  "The short end of the stick",
  "The shot heard 'round the world",
  "The sky's the limit",
  "The smallest room in the house",
  "The tail wagging the dog",
  "The toast of the town",
  "The third degree",
  "The triumph of hope over experience",
  "The upper hand",
  "The usual suspects",
  "The whole kit and caboodle",
  "The whole nine yards",
  "The whole shebang",
  "The writing is on the wall",
  "The year dot",
  "The Yellow Peril",
  "There is more than one way to kill a cat",
  "There is no alternative",
  "There's an R in the month",
  "There's no such thing as bad publicity",
  "They couldn't hit an elephant at this distance",
  "Thick and thin ",
  "Thin air",
  "Thing of beauty is a joy forever",
  "Things that go bump in the night",
  "Think outside the box",
  "Thinking cap",
  "Third degree",
  "Third time lucky",
  "Thorn in the flesh",
  "Thou shalt not kill",
  "Three score and ten",
  "Three sheets to the wind",
  "Three strikes and you are out",
  "Through thick and thin ",
  "Throw in the towel",
  "Throw your hat into the ring",
  "Thumbs up",
  "Thus far into the bowels of the land",
  "Ticked off",
  "Tickle the ivories",
  "Tickled pink",
  "Tide over",
  "Tie the knot",
  "Till the cows come home",
  "Time and tide wait for no man",
  "Tinker's dam",
  "Tilting at windmills",
  "Tissue of lies",
  "Titfer",
  "Tit for tat ",
  "Tits up",
  "To a T",
  "To all intents and purposes",
  "To beggar belief",
  "To big for your breeches",
  "To boldly go where no man has gone before",
  "To boot",
  "To cast the first stone",
  "To the manner born",
  "To the nth degree ",
  "To travel hopefully is a better thing than to arrive",
  "Toast of the town",
  "Toe the line",
  "Tomorrow is another day",
  "Tongue in cheek",
  "Too much of a good thing",
  "Top dog",
  "Top drawer",
  "Top notch",
  "Total shambles",
  "Touch wood ",
  "Tout de suite",
  "Tower of strength",
  "Trick or treat",
  "Trip the light fantastic",
  "Trouble and strife",
  "True blue",
  "Truth is stranger than fiction",
  "Truth will out",
  "Tuckered out",
  "Turn a blind eye",
  "Turn of phrase",
  "Turn the tables",
  "Turn up for the books",
  "Turn up trumps",
  "Twelve good men and true",
  "Twenty three skidoo",
  "Twenty four seven",
  "Two cents worth",
  "Two heads are better than one",
  "Two peas in a pod ",
  "Under the thumb",
  "Under your hat",
  "Uneasy lies the head that wears a crown",
  "Up a blind alley",
  "Up a gum tree",
  "Up shit creek without a paddle",
  "Up the apples and pears",
  "Up the duff",
  "Up the pole",
  "Up the wooden hill to Bedfordshire",
  "Up to snuff",
  "Upper crust",
  "Upper hand",
  "Up in arms",
  "Upside down",
  "Urban myth",
  "Usual suspects",
  "Using a sledgehammer to crack a nut",
  "Valentine's Day Poems and Sayings",
  "Vanish into thin air",
  "Veg out",
  "Vice versa",
  "Vicious circle",
  "Vorsprung Durch Technik",
  "Walk free",
  "Walk the walk",
  "Walk the plank",
  "Walter Scott",
  "Warts and all",
  "Watch the birdie",
  "Watching brief",
  "Wave a red rag to a bull",
  "Wax lyrical",
  "Wax poetic",
  "We are a grandmother",
  "We are not amused",
  "We have seen better days",
  "We know where you live",
  "Weakest link",
  "Wear the trousers",
  "Wear your heart on your sleeve",
  "Weasel words",
  "Well heeled",
  "Well read",
  "Wet behind the ears",
  "What a piece of work is man",
  "What God has joined together let no man put asunder",
  "When it comes to the crunch",
  "When pigs fly",
  "When the shit hits the fan",
  "Where there's muck there's brass",
  "Whet your appetite",
  "Whistle and flute",
  "Whistle down the wind",
  "White as snow",
  "White bread",
  "Whipper snapper",
  "Whipping boy",
  "White elephant",
  "Whole kit and caboodle",
  "Whole nine yards",
  "Whole shebang",
  "Why does bread always fall butter side down",
  "Wick",
  "Wide berth",
  "Wild and woolly",
  "Wild goose chase",
  "Willy nilly",
  "Win hands down",
  "Win one for the Gipper",
  "Wing it",
  "Winter drawers on",
  "Wish you were here",
  "With bells on",
  "Without let or hindrance ",
  "Without so much as a by your leave",
  "Woe betide you",
  "Woe is me",
  "Wolf in sheep's clothing",
  "Woman needs a man like a fish needs a bicycle",
  "Woman's place is in the home",
  "Women and children first",
  "Wooden hill to Bedfordshire",
  "Word association football",
  "Word for word",
  "Word in edgeways",
  "Words ending in gry",
  "Worse for wear",
  "Worth one's salt",
  "Wotcher",
  "Writing is on the wall",
  "Yada yada",
  "Year dot",
  "Yellow Peril",
  "You are what you eat",
  "You can lead a horse to water but you can't make it drink",
  "You can lead a whore to culture but you can't make her think",
  "You can't get blood out of a stone",
  "You can't teach an old dog new tricks",
  "You get on my wick",
  "You look as if you've been dragged through a hedge backwards",
  "You'll wonder where the yellow went when you brush your teeth with Pepsodent",
  "Young turk",
  "Your money or your life",
  "Your name is mud",
  "You've never had it so good",
  "Zero tolerance",
  'A stitch in time saves nine'
];
